# Generated by Django 5.1 on 2025-02-28 22:44

import app_pedidos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('peso', models.FloatField()),
                ('valor_unitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(default=app_pedidos.models.generar_numero_orden, max_length=10, unique=True)),
                ('valor_total', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente')),
            ],
        ),
    ]
